### ISSUE TITLE
How to archive Sale Off cases

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#102]
Laurence pointed out that the only way in Jinn to take a rent out of case status is (from the rents page) to "View Case" and then "Archive Case".  The code was hard wired to delete the row in the cases table and to switch the rent Status from "C" Case to "A" Active.  Unfortunately, almost all cases of CaseType "S" Sale Off end when the sale has been completed **and the status of the rent needs to be changed to "S" Sold off.**  At MCS, this unhelpful behaviour was not noticed and some unfortunate householders received a further rent demand in a MPR run, even though they had bought out their rent.

I have just pushed a fix to GitHub which will make sure that all Cases of CaseType S will be archived with the rent status now being switched to "S" Sold off, not "A" Active.  What would be nice would be for the user to see an improved dialog during the "Archive Case" process making clear the default rent status which will be applied but allowing the user to select from a combo box if he or she wishes to override the default rent status which will be applied.

**Comment by jnbarchan** [comment]
Re-opened and tidied up last bits.
