### ISSUE TITLE
Problems with charges on rents page

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#110]
RH originally opened this issue because of several problems which arose after we decided to do away with the charges_arc table and add the ChargeStatus field to the charges table.  Although we have fixed the most serious problems, neither Laurence nor RH are confident of taking the final clean up step of removing the ChargeStatus field from the charges table and correcting the code so that any charge which is fully paid up must henceforth be immediately deleted.  We thought it best for JNB to do this, as we will need another db upgrade script to alter the table.

Just for the record:  We persisted in keeping a fully paid charge for a few weeks **in case the cheque bounced**, with the idea that charge could then be recreated from the old charge.  After much debate, all the users have agreed that this is completely unneccessary: 1. because it is a very rare occurrence. 2. because the charge can easily be recreated from the income_allocation table and 3 because the paid up charge appearing in the charges table on the rent page is universally hated.

I believe Laurence may have already altered the code so that the charge is now recreated from the income_allocation table rather than from the paid up charge with ChargeStatus = 0, as was the riginal idea.  So, all that JNB needs to do is:

1. Check carefully that the code can be corrected to hold no further reference to ChargeStatus.

2. Create a suitable db upgrade script so that the next Jinn start up will delete all charges with ChargeStatus =0 and then restructure  the charges table to remove the ChargeStatus field.

Hopefully, I have now removed the confusion caused by me editing the original issue after Laurence made some comments and did some fixing.

**Comment by LaurenceLeo** [comment]
This is not actually an issue with the method "clearCharges" in income/incomefunctions.py. Even though this method is called in line 165 I do not believe it actually acts upon anything. This is because in lines 146 to 152 in income/incomeposter.py set a ChargeBalance that is **NOT** zero. This means that "clearCharges" does not effect the generate charge since it only alters charges with ChargeBalance zero.

Here is the code causing the issue:

                    charge_no = dbHandler.insertID("""INSERT INTO charges
                                                         VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)""",
                                                         (None, rent.info['RentCode'], chargeType, postingDate, amount,
                                                          "£{} {} created and cleared on {}".format("%.2f" % amount,
                                                          incomeLine.cb.currentText(),
                                                          dateToSlash(dateFromDash(postingDate))),
                                                          amount, 0, postingDate))

Here you can see we are not inserting a ChargeBalance of zero, but one of "amount". We are also inserting a ChargeTotal of "amount". Here is an example from my log using a noticefee of £60.00.

```
INFO dbLogger [database.py, 178, log()]: InsertID: 'INSERT INTO charges
                                                         VALUES (None, DUMMY, 3, 2018-09-17, 60.00, £60.00 Notice Fee created and cleared on 17/09/2018, 60.00, 0, 2018-09-17)
```'
To solve this issue I would recommend changing the insert value for ChargeBalance to zero here. So make this. 


                    charge_no = dbHandler.insertID("""INSERT INTO charges
                                                         VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)""",
                                                         (None, rent.info['RentCode'], chargeType, postingDate, amount,
                                                          "£{} {} created and cleared on {}".format("%.2f" % amount,
                                                          incomeLine.cb.currentText(),
                                                          dateToSlash(dateFromDash(postingDate))),
                                                          0, 0, postingDate))

**Comment by LaurenceLeo** [comment]
We have considered moving forwards to a DB structure where cleared charges are deleted instead of set from ChargeStatus = 1 to 0. 

This needs further discussion.

**Comment by jnbarchan** [comment]
1. Checked all references to `ChargeStatus` in code.  All were about `ChargeStatus = 1`, so no problem.

2. Upgrade script first deletes any rows in `charges` which have `ChargeStatus = 0`, then drops the `ChargeStatus` column.
