### ISSUE TITLE
Improve DateCode handling

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#111]
In all of the places where the user is in a dialog where the DateCode needs to be entered or edited, we need Jinn to insert the only matching datecode based only upon the values in LastRentDate and Frequency.  **Although extremely rare, the code should offer the user a choice of possible datecodes in the exceptional Ben Sparrow case set out below.** The main dialogs which spring to mind are `Edit rent`, `Edit head rent`, `Add rent and property`, `Add rent` and `Add head rent`.  Please ignore anything arising from the `Rents/properties (deprecated)`  button on the Utilities page - it needs to go.  Please note that there is no dates table for Frequency = 1, as the next rent date is always equal to LastRentDate plus one year, so LastRentDate = "09/01/2018" and Frequency = 1 means that DateCode = F1Jan09A.  There can therefore never be a F1 DateCode ending in anything but "A".

For instance, if LastRentDate = 29/09/2018 and  Frequency = 2, the code will go to the dates_f2 table and find only one record with a date of 29th September, meaning that the DateCode must be F2Mar25A, so that value should be inserted in the DateCode box with no need for the user to have to choose from a list.  This will be the case for all my F2 cases and all my F4 cases, as I have no value which ends in a "B".

**Exceptional case:**  Ben Sparrow has one F2 record only with a date value ending in "B" .  The two relevant records are:

F2Jun30A | 2000-06-30 | 2000-12-31
-- | -- | --
F2Jun30B | 2000-06-30 | 2000-12-30

You will see that the code needs to offer the user a choice of two datecodes if the value in LastRentDate is found in more than one record in the corresponding dates table.  The only case for Ben would be when LastRentDate = "30/06/2018" and Frequency = 2.

**Comment by jnbarchan** [comment]
Did it for **Edit rent** dialog.:

* Re-factored `rentlogic/resolveDateCode()` (which was only used when adding a new rent from **Rents/properties (deprecated)**) to call lower-level `dateCodeChoices()`.
* Changed code to *correctly* look up in `dates_F[24]`, which it was not doing (in the Add rent case).
* Changed code to use cached dates DataQuerier.

At this point I am pushing my changes for H. to have a look at.  Then I will proceed to the other dialogs mentioned above which need doing.

**Comment by jnbarchan** [comment]
- Did same for Head rents.  I claim this is the only other place Jinn has  a selectable datecode.

- Also did at same time so that message box dialogs have an expanding height (not width) on their potentially multi-line informative text, so that it does not have to be scrolled.  E.g. see the `AreYouSureDialog` when about to **Restore database**.
