### ISSUE TITLE
email check box on MPR selected run page does not display rents with valid email

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#115]
Go to the MPR start page and double click ALLAN - this will take you to the MPR selected run page

Change the end date from 11/11/2018 to 11/10/2018

Filter for RentCode "ZAKC"

Double click on  ZAKC17 - this will open that rentcode on the Rent page and you will see that this rent does have a valid email address

Go back to the MPR selected run page and tick the Email checkbox - you will see that no rents are displayed, even though ZAKC17 and other rents with a valid email address should be displayed

**Comment by jnbarchan** [comment]
The clause added to the condition when the **Email** box is checked should be correct.  However it seems to behave incorrectly on `ZAKC17` (no agent email).  I have had to raise a question on this at **stackoverflow** (https://stackoverflow.com/questions/52535846/mysql-left-join-with-where-function-call-produces-wrong-result), and await responses in hope..
