### ISSUE TITLE
Use Jinn to open and "Edit" Pdf files

### ISSUE THREAD

**Issue by LaurenceLeo** [hezmondo/Jinn#130]
It's a common issue for our users that PDF files cannot be edited after saving. This is due to Adobe being difficult and insisting on "money". I have found several Python modules that will enable us to read from our previous PDF files. This should enable us to populate a letter/email preview window with the text from a previous letter. We can then save over our previous letter as a form of PDF "editing".

One such Python module is PyPDF2.

**Comment by jnbarchan** [comment]
* Why would anyone want to edit these PDF files?

* Why would anyone want to edit "previous PDF files"?

* Why would you you want to integrate editing into Jinn/Python?

* What is the purpose of this issue?  What is there supposed to be to do?

* In general, why do you want to make Jinn as complicated as possible? :)

**Comment by LaurenceLeo** [comment]
I must concede the point. This is indeed an unnecessary enhancement.
