### ISSUE TITLE
Epr page is failing to setQuery in payreqpage.py 

### ISSUE THREAD

**Issue by LaurenceLeo** [hezmondo/Jinn#138]
After a payrequest preview is done on the MPR Selected Run screen I get this message.

Unhandled Exception:

'NoneType' object has no attribute 'setQuery'

<class 'AttributeError'>
  File "C:\HJinn\Code\epr\eprpage.py", line 712, in trialRun
    self.refreshEprRuns()
  File "C:/HJinn/Code/home.py", line 790, in refreshEprRuns
    self.payreqPage.refreshTables()
  File "C:\HJinn\Code\payrequests\payreqpage.py", line 342, in refreshTables
    self.setPayReqRunQuery()
  File "C:\HJinn\Code\payrequests\payreqpage.py", line 146, in setPayReqRunQuery
    self.modelPayReqRun.setQuery("""SELECT er.runcode AS 'Run code', `Order`, Description,

Error logged and operation aborted

I have a feeling this is due to the method at line 103 in payreqpage.py not activating as it is supposed to. I have assigned Jonathan to this as I do not understand the method/function? used in eprpage.py to start this behaviour:

self.refreshEprRuns = lambda: None

Sorry I cannot detail what this is supposed to do properly.

**Comment by jnbarchan** [comment]
This has nothing to do with the line in `eprpage.py`.  Rather, `self.modelPayReqRun` has not been initialised.

The *only* way I can get this to happen is to run Jinn and go straight into **MPR Selected Run** *without* having visited the **MPR Start** page at all.  H. has declared that is "invalid".  We can tighten something up if required, but he didn't seem too bothered about users knowing they must start out from **MPR Start**.

Please confirm this is the case, or give precise instructions to produce the error if otherwise?

**Comment by LaurenceLeo** [comment]
I disagree with H. We have spent a decent amount of time empowering the search methods in MPR Selected Run. This means that users can create their own selections on the fly without having to use MPR Start. As I mentioned before, this issue has be reported to me separately by both MCS and HMCC. 

To reproduce the go to the MPR Selected Run screen, without using MPR Start. Then add any filter so that you have some search results. Restrict your results to a manageable number (so that it does not run  for ages). Then select either "Preview" or "Run". After either process is finished. You will get the error:


Unhandled Exception:

'NoneType' object has no attribute 'setQuery'

<class 'AttributeError'>
  File "C:\HJinn\Code\epr\eprpage.py", line 714, in trialRun
    self.refreshEprRuns()
  File "C:/HJinn/Code/home.py", line 790, in refreshEprRuns
    self.payreqPage.refreshTables()
  File "C:\HJinn\Code\payrequests\payreqpage.py", line 342, in refreshTables
    self.setPayReqRunQuery()
  File "C:\HJinn\Code\payrequests\payreqpage.py", line 146, in setPayReqRunQuery
    self.modelPayReqRun.setQuery("""SELECT er.runcode AS 'Run code', `Order`, Description,

Error logged and operation aborted


I will talk to Hes as I think this is an issue we should sort out

**Comment by jnbarchan** [comment]
Then I can doubtless/presumably change code such that `self.modelPayReqRun` is initialised so it does not error in this case.  What I cannot say is whether the code in general is "happy" to work this way without having visited *MPR Start* beforehand, e.g. if that is required to set anything else up.  That is for you (two) to decide, and then let me know if you want me to sort out the variable?

**Comment by LaurenceLeo** [comment]
This is a result of a design issue. After discussions with RH, this is not a crucial issue. We will return to this at a later date when MPR is redesigned.
