### ISSUE TITLE
epr page context menu preview selection is faulty

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#140]
Unless I am doing something wrong, right click and select "preview" option results in a pdf file with no header and no footer.

**Comment by LaurenceLeo** [comment]
This was due to the variables "isEmail and isLetter" not being set in mergeDict. This meant that mergeconditionals did not merge the correct header html fragments. I have pushed a fix to HJinn. Now the context menu prompts for preview Email or preview Letter. I am closing this issue.
