### ISSUE TITLE
Improve email routine for letters and pay requests

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#142]
Problem 1 - Peter has asked if  we can provide an autocomplete facility on all three email address boxes in the Recipient information dialog (letters/recipientdialog.py), using partial match when blank or blanked and three characters then typed.

Problem 2 - All users are vexed by having to copy the tenant's email address from the top right of the rent page to the agent's email address, for buy to let landlords who do not live at the property.  Tiresome and stupid, as the agent is actually the tenant - he just has a **different postal address!**

Here is my recommended solution having listened carefully to J's comments on my more radical overhaul suggested earlier today:

1. I agree we leave the contacts.Email field to hold the tenant's email  address.

2.  I agree we leave the the agents.AgentEmail field to hold the agent's email address **only for those cases where a) the agent is not the tenant or b) we do not not want an emailed letter or pay request to go to the tenant email address**.

3.  Now this leaves us free to create a very simple new table non_tenant_email_addr to hold all email addresses that have ever been used by Jinn OTHER THAN any tenant email address in contacts.Email, as **this table will not now have any back reference to rents, agents, or any other Jinn table**.  It is there to do one job only, which is to offer efficient autocomplete options for a blank or blanked email box in the recipient dialog.  It need only have id and value.  It could be populated at first with all email addresses extracted from Actions.ActionDetails **LESS any tenant email address in contacts.Email** and possibly by downloading all the email addresses used by the user business email account, if that is possible, again **LESS any tenant email address in contacts.Email**.  Thereafter, it will be populated further by adding any email address used by Jinn which is not in contacts.Email and is not already in the table.  

This leaves the remaining problems raised by J:- how to help the user who cannot be bothered to copy the buy to let tenant email address to the agent (actually still the tenant as a different mailing address) address and how to cater for the relatively rare situation where we want to email only the agent.

Unbelieveably simple and brilliant solution:

The user will no longer need to copy the tenant email address to the agent.Email field for the very common case where the agent is the tenant.  Jinn will simply send any email to the tenant email address and the agent email address for all values of MailToType **other than the new value X = "Mail to agent only"**.

Am I a genius or what?

**Comment by jnbarchan** [comment]
* Does not answer where "hold all email addresses that have ever been used by Jinn" actually comes from?  Does this mean (something like) from the **Recipient Information** dialog add anything typed into the **To** or **Cc** lines?  Anywhere else?

* And/or, are any email **Cc** addresses now to be included in the `Actions.ActionDetails` logged from Jinn?

* The rest of the Issue, where it talks about removing items from the list, introducing some new value for **MailToType** which is never mentioned before, is unclear and pretty complicated as phrased.  I cannot implement it from this description, and will require further clarification.

**Comment by hezmondo** [comment]
For all subsequent emails and all recipient email addresses on the dialog:   IF emailaddress NOT IN contacts.Email AND emailaddress NOT IN new_email_table INSERT INTO new_email_table.  No other case need be considered.

I have just checked and confirm that only the first email address on the dialog is recorded in actions.Actiondetails, as **Email RECSTA written to 'abcd@gmail.com'**  I suggest we include the cc emailaddresses and drop the "written" and the quotation marks, ie *Email RECSTAT to abcd@gmail.com cc fhkl@talktalk.com cc nopq@aol.com**

I cannot see any further clarification being needed to my suggestion for automatic email behaviour, for instance in the case of a batch of pay requests to be sent in on go with pdf attachments.

**Comment by jnbarchan** [comment]
After long discussion with H., here is what we have agreed needs to be done for this Issue:

1. Introduce some new `email_addresses` table.
2. Populate it during the Upgrade "as best we can" from what is currently in  `actions.ActionDetail` with "simple parsing" (only email addresses inside `'` (single-quote) characters), but *exclude* any email addresses which are already present in `contacts.Email`.
3. Whenever user puts an address into **Recipient Information** dialog, whether as **To** or **Cc**, add that to the email addresses table, but again *exclude* any in `contacts.Email`.
4. Whenever user adds/alters the email address from **Agents** page, also add as per preceding point.  Never delete from the email addresses table.

Anything else here (e.g. **MailToType**, including **cc* email addresses in logged `actions.ActionDetail`) to be done on some other Issue.

**Comment by jnbarchan** [comment]
All done.
