### ISSUE TITLE
IMAP - Timeouts

### ISSUE THREAD

**Issue by LaurenceLeo** [hezmondo/Jinn#145]
I have observed an issue occurring where users have poor connection speed (MCS). I have altered MCS's timeout in the "email_accounts" table to 60 seconds, the 20 seconds used before was too short. 

They have an odd issue where SMTP succeeds but IMAP fails. This is likely due to **IMAP timing out.** The only cases where this error has occurred is when there is a large attachment requiring upload. I have been able to reproduce the error. 

This is the error code:

Problem copying message to email folder: socket error: [WinError 10053] An established connection was aborted by the software in  your host machine

This is not a serious error, but I would like to record it in-case it becomes a problem. I have since increased MCS timeout to 120 seconds.

The information on WinError 10053 is as follows:

WinError 10053
Software caused connection abort.
An established connection was aborted by the software in your host computer, possibly due to a data transmission time-out or protocol error.

I think this points towards our socket being closed during the IMAP upload.

**Comment by jnbarchan** [comment]
@LaurenceLeo 
Is this actually a "bug" as you've classified it?  A bug to me means a software coding error which can be rectified.  In this case are you just describing normal behaviour/their system's behaviour/their provider's (you should include the provider in this information, I think, as it may be fine elsewhere?) behaviour?  Is there anything to change in the code to address this?

**Comment by LaurenceLeo** [comment]
I am actually not sure what to label this as. Their IMAP service is controlled by 1&1. I actually hadn't considered that their upload speed via IMAP might be slower due to 1&1's IMAP working slower than their SMTP. 

I am not actually sure if there is an issue here. Just wanted to highlight what happened in-case it occurred multiple times. I'll remove this issue in a week or so if it doesn't rear its' head again.

**Comment by jnbarchan** [comment]
That's fine, but I wouldn't classify it as a "bug", especially if there's nothing (more) we can do about it.  Issues marked "bug" I'd like to be able to fix, and soon-ish.

I've created a new "informational" label just now, and re-tagged this,.
