### ISSUE TITLE
Income page filtering does not work correctly

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#148]
Go to income page and click "All".  A very long time ago, you could filter the records by Bank and by Ptype by clicking on the column heading, which would then filter according to the corresponding value in the selected row.  If this facility could be restored, then that would be great.  If not, we could go back to the more robust idea of adding one or more combo boxes at the top.

To summarise:  It would be a great improvement if we could quickly and easily filter all income records by Ptype - eg just Cheque or just BACS.  Even better if we could also filter for a specific bank account.

**Comment by jnbarchan** [comment]
This has always worked by clicking in *cells* rather than selecting whole *rows* (*not* clicking on column headers), and then clicking on **Filter By Selection**.

I have restored that behaviour, so that you can select individual cell(s) rather than whole row(s).
