### ISSUE TITLE
Improvement needed to Headrents page

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#149]
This was on Peter Clarke's list of known faults/omissions. Go to Headrents page, filter for agent "COMPT" and status = "A", which will give you some valid headrents which have had recent payments.

Click "Past payments" and you will get the "not yet implemented error".

What we need is a results table listing relevant information for all past head rent payments which included an allocation for this head rent code, with the ability to export the results to csv and pdf, just like income queries and money transaction queries.  Here is my Workbench query which provides me with the info I need:

SELECT a.PaymentDate, a.PaymentTotal, a.Payee, a.BankType, a.PaymentType, a.Periods, 
ROUND(((c.Rent*a.Periods/c.Frequency) + b.Arrears),2) AS Allocated, b.HRCode 
FROM yoda.hrpayments a 
LEFT JOIN yoda.hrpayments_hrcodes b
ON a.PaymentID = b.PaymentID
LEFT JOIN yoda.headrents c
ON b.HRCode = c.HRCode 
WHERE b.HRCode = "COOP1M"
ORDER BY a.PaymentDate
;

**Comment by LaurenceLeo** [comment]
I'm happy to do this and almost have it finished. I just want to clear up the output so that it as useful as possible.

**Comment by LaurenceLeo** [comment]
I have added a pyfile that produces a Jtableview and can export its results to CSV or PDF.
