### ISSUE TITLE
Fixes from Agents page

### ISSUE THREAD

**Issue by jnbarchan** [hezmondo/Jinn#204]
From **Agents** page, **Add Agent**:

1. In **Add agent** dialog, with a bad code for **Agent code** (e.g. the default `001` that gets populated there) click **Save**.  After the warning about bad code, make a legitimate code and click **Save** again.  Get error:
```
Transaction oddity
An attempt has been made to start a new database transaction before the previous one was finalised.
Jinn will continue and everything will probably be fine, but please alert the authorities to this message and provide your log file so they can investigate.
```

2. Pick an agent with some associated rents.  Select one of the rents. Click **Change agent linked to rent**.  Now pick **New Agent**.  Nothing seems to happen in this case (I was expecting an "enter new agent details" dialog).

3. From H.:

> The AgentCode is "meaningful" in Jinn (eg the Headrents module stores the pdf remittance advices in the HRPayments folder in a folder named as the first 5 characters of the AgentCode) and should ideally comprise the first five alpha characters of the agent name followed by three numbers - eg Compton Group having agentcode COMPT001.  The old code used this idea and still does if, on Agent page, you type in ABCD into agent details (getting no matches) and click "Add agent".  The new code should really stick with this idea in L's new dialog (maybe ask user for first 5 chars?).

**Comment by jnbarchan** [comment]
1. Fixed.

**Comment by LaurenceLeo** [comment]
I have just tried these two issues and found they don't occur in my code. I'm not sure why. I would check that your version of agentspage.py is similar to mine.

**Comment by LaurenceLeo** [comment]
My idea was that a user could change agent to a new agent, creating this agent on the fly and then assigning it. 

To do this I implemented methods in the AgentsPage. This was the only way I could think to avoid circular imports since both dialog can essentially open each other:

User edits agent, then changes agent, decides on a new agent:

EditAgentDialog>ChangeAgentDialog>EditAgentDialog(as add agent)

Also when a user selects a rent with no agent. Here we open the ChangeAgentDialog so they can select an agent if they have one in mind or create a new one to assign.

ChangeAgentDialog>EditAgentDialog(as add agent)

**Comment by jnbarchan** [comment]
L. wrote:
> I have just tried these two issues and found they don't occur in my code. I'm not sure why. I would check that your version of agentspage.py is similar to mine.

They occur as described in the code as pushed.  I got H. to verify yesterday these happened for him too.  I have just compared my present versions of the files against the current `LJInn` branch, and the only changes are those I have made in my own edits so far.

Maybe it is your local code which is not identical to that which has been pushed?

**Comment by LaurenceLeo** [comment]
I think I might just not be triggering these errors correctly. I would just ignore what I said, my code is the same as on LJinn.

**Comment by LaurenceLeo** [comment]
I have retried creating these errors and have succeeded! I seem to be unable to follow instructions exactly. The error that seems to be happening is the setting of **self.rentCode** in the editagentdialog. This **only** occurs when I start in the **agentspage**.

The **editagentdialog** takes its rentcode from the rent you open it from in **rentpage**, since here we are opening from the **agentspage** this is not set. So opening the **editagentdialog** here and clicking change agent will throw an error. It might be worth hiding this button when accessed from the **agentpage.**

I get the same error as you when I do:

AgentsPage>EditAgentDialog>ChangeAgentDialog>Nothing/Error

I think this is due to **self.referredRentCode** not being set in the method **editAgent** (line 267). 
I'm not working on this but thought I'd pass on some info. Thanks.

**Comment by jnbarchan** [comment]
`editagentdialog/validateFields()` was doing a database `UPDATE` (now outside of any transaction), which was a bad idea anyway.  H. does not want agent codes to be "renamed" once created, just like rent codes etc.  Made that edit widget read-only if editing an existing agent.

**Comment by jnbarchan** [comment]
The existing code was a bit of a mess, failing to function correctly in a variety of circumstances (new agents, changing from no agent to an agent, invoking from the **Agents** page as opposed to from a rent on the **Rents** page, ...  I have tidied those up so it's consistent & working to the best of my ability.

Meanwhile, after talking with H., we identified that the **Edit Agent** can be invoked in one of two distinct ways, and should be altered accordingly:

1. Starting out from a single rent.  This can be from the **Rents** page via **Agent**, or from the **Agents** page where selecting a linked rent and **Change agent linked to rent**.

2. Starting out from the **Agents** page, selecting an agent and **Edit Agent**.

**Comment by jnbarchan** [comment]
At this point, having spent weeks trying to sort everything out without destroying, I am pushing my work.  You can't make a silk purse out of a sow's ear, or knock a square peg through a round hole, and I won't deny it's been very difficult and my changes still doubtless leave something to be desired.

Basically I claim to have implemented as per above, i.e. distinguished the usage against a specific rent vs against the agent as a whole and all its rents.  I hope it mostly works.  It should *not* error anywhere, but it may be that after an agent/rent some visual tables do not get updated thoroughly/in all cases.

It should be tested in *all* combinations: starting from *Rents* page (both from a rent which does have an agent and from one which does not) and from **Agents** page, adding/deleting rents, changing agent, change to a **New agent**, etc.

If this proves not robust enough, we might have to scrap all code written since trying to add to original Jinn's **Agents** page and start afresh... :(

**Comment by LaurenceLeo** [comment]
Hey Jonathan. Thanks for sorting this out, I am sorry you have had so much work to do. When I first uploaded this code it was only so that I could get feedback from H on what he thought the GUI looked like and how the dialogs handled user flow. I was then planning on working on it at a later date. Thanks for your work.

**Comment by jnbarchan** [comment]
From H.:

 am using the latest code as currently on Master and Hjinn.  So far, I have tested:

**Working from Agents page:**

* Delete agent with one linked rent and unlink the rent - works fine
* Delete agent with no linked rents - works fine
* Edit agent with one linked rent - works fine
* Unlink one rent from agent with many linked rents, using manage linked rents tab, changing to an existing agent - works fine
* Unlink 2 rents from agent with many linked rents, using manage linked rents tab,changing to an existing agent - works fine
* If I click the "change agent linked to rent" button at bottom right on agents page to unlink one rent from an agent with many linked rents, changing to an existing agent , it works but does not refresh the rents table, so leaving the changed rent still showing for the first agent


**Working from rents page:**

* Change agent for rent linked to existing agent to another existing agent - works fine
* Double click "MAIL TO SET AS AGENT BUT NO AGENT FOUND!" and choose an existing agent - works fine
 
* Double click an existing agent which has only that rent linked, select "Unlink agent from NEE71", click "Yes":
I now get the "Delete agent" dialog saying there are now no rents linked with this agent, so, "would I like to delete this agent?": my options are only OK or Cancel, but I would like the options "Yes" and "No".  I click Cancel (because I do not wish to delete the agent) and I am back in the "Edit agent" dialog with the rent still showing as linked to the agent. I  have no Close button, so I close the dialog. The outcome is fine: I have succeeded in unlinking the agent and now correctly see "MAIL TO SET AS AGENT BUT NO AGENT FOUND!" and the agent remains undeleted. This is an unusual case, but I think we could improve the code greatly by:
1 - adding a "Close" button to the "Edit agent" dialog
2 - changing the "Delete agent" dialog to offer just two choices to the question "Delete agent?", being "Yes" and "No" and then preferably taking the user back to the rent page, not to the "Edit agent" dialog, as the user has done what he wanted to do.  If we have to go back to the "Edit agent" dialog, we need it to refresh this to show that the rent is no longer linked to any agent and also have the Close button, which will be what we will almost always click.

**Comment by jnbarchan** [comment]
> If I click the "change agent linked to rent" button at bottom right on agents page to unlink one rent from an agent with many linked rents, changing to an existing agent , it works but does not refresh the rents table, so leaving the changed rent still showing for the first agent

Fixed.  For complex reasons, for right or for wrong the **Agents** page will stay on viewing the original agent, not the one newly linked to, but at least the rents table at the foot is now updated, so you won't see the orinial rent code there any longer.
