### ISSUE TITLE
Size of some pages too large for small laptop displays

### ISSUE THREAD

**Issue by jnbarchan** [hezmondo/Jinn#211]
H. reported:

> Leaving aside the button message display issue, I have found that the MPR selected run page is the elephant in the room.  The problem for me or R. on our Lenovos is this:  once we have clicked the MPR selected run page, we can no longer resize Jinn, even if we close Jinn and restart.  The only way I have found to get round it is to close Jinn, open a terminal, `cd ~/.config/JinnSoft`, `sudo rm Jinn.ini` and then restart Jinn.  I will be happy to do some simple alterations to reduce the width of the MPR selected run page to deal with this immediate issue.

**Comment by jnbarchan** [comment]
I will address this straight after finishing the modeless later this week.  We said one thing I can do is make it so it tells you (debug output) whenever a page you open gets too big for your display.  We could also put in more checks to make it so it will not save the last page size resized to if the dimensions would exceed those of the host display, so that one does not have to delete the saved dimensions file.

**Comment by hezmondo** [comment]
Jinn debug window on Lenovo laptop states available Jinn geometry to be 1364 X 635 pixels

have just pushed short term GUI corrections to two screenns which were too high/deep for lenovo

**Comment by jnbarchan** [comment]
Introduced a means (for development) of *pretending* what the desktop size is, to correspond to some other device:

In  `settings.ini`, `[Debug]` section:
```
# pretend_desktop_size: set to WxH (e.g. 1364x635) to receive debug warnings if it ever exceeds this (for development)
pretend_desktop_size =
```
(Default is "empty" if this entry not present.)  Setting this to some **WxH** allows you to test for exceeding the specified size.  Whenever Jinn is started/windows are resized a debug warning message will be issued if the new size exceeds this.  If this entry is empty the actual (available) desktop size is compared against.

**Comment by jnbarchan** [comment]
Wrote class `widgets.CheckDesktopGeometry` to manage this.  Code should call `CheckDesktopGeometry.checkWindowSize()` on every resize.

I defined overrides `JDialog.resizeEvent()` & `Main.resizeEvent()` to call this.  That covers all our dialogs and the main window which includes all pages shown in the `QStackedWidget`.  I could have defined a `QApplication.eventFilter()` to capture these and any other resize events which might happen if there are other classes I have not thought about, but since we don't have another need for a global event filter I stuck with the class overrides.

I should also go through our explicit `.resize()` calls and warn about these, so that the traceback picks these out.  We seem to have quite a few already which will exceed the minimum window device size.  Some of those could be reduced or even removed completely?

**Comment by jnbarchan** [comment]
* Changed all window `resize()` calls over to using `JDialog.setInitialSize()`.

* Changed all dialogs over to using a fixed initial size, instead of some of them using `desktopSizer()` to specify a size relative to the desktop size.  Most applications use fixed sizes for dialogs, not desktop-relative.  Makes it easier to design/maintain size needed.

* Got rid of places where some dialogs used `setSpacing(15)` if `isHighDef()` is true.  Again, makes dialogs easier to design/maintain.

**Comment by jnbarchan** [comment]
[Unrelated fixes]
* Fixed `updatecode.py` to flush prompt to terminal.

* Fixed all uses of icons so that they access the full path correctly instead of a relative path, which did not work if the current directory was not the `Code` folder.
