### ISSUE TITLE
AC error - moves rent date forward and adds rent arrears

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#214]
The PR code needs fixing on two counts:  

1. Undo PR does not work for AC (see previous issue)

2. I just produced an AC for two charges (both buildings insurance premium) with no rent arrears.  The AC was fine, showing the two charges owing and the corrrect total.  Hoever, when I went back to the rent I saw that the rent date had been rolled forward and one period of rent added into the previously zero arrears  field.

**Comment by LaurenceLeo** [comment]
This was a mistake I made in **mailvariables.py**. At line 445 I have incorrectly set the "MailingType" in dataDict to MailingType.Pr as default. It should be prAc.

So this line:
   `"MailingType":` MailingType.Pr,`

Should be:
   `"MailingType": prAc,`
