### ISSUE TITLE
MPR selected run page could use additional filter for Landlord 

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#215]
Ben pointed out that the MPR selected run page could use an additional filter for Landlord.  Not urgent.

**Comment by jnbarchan** [comment]
I pointed out to H. that, at least for the minimal 1364x635 desktop size we support, this will mean another row for the filters on the **MPR Selected Run** page.  He seemed OK with that, and liked the idea that I make these rows be in a horizontal flow box which can wrap vertically as needed, i.e. it will only take up as many rows as it needs depending on desktop width.  Once we have implemented that it will make it easier to add/remove filters if we need to.

**Comment by jnbarchan** [comment]
Oh dear!  My assumption that some Qt layout/widget would exist to provide "flow"/"wrap to next line down" automatically (like an HTML `<DIV>` element) proves ill-founded!  See my thread https://forum.qt.io/topic/104653/how-to-do-a-no-break-qhboxlayout.  We would need to implement the example (https://doc.qt.io/qt-5/qtwidgets-layouts-flowlayout-example.html, https://code.qt.io/cgit/qt/qtbase.git/tree/examples/widgets/layouts/flowlayout), into Python.

**Comment by jnbarchan** [comment]
I am first implementing the sample flow layout in Issue Fix #237.  Then I will return here and use it to solve this issue.

**Comment by jnbarchan** [comment]
Did that, at least such that it seems to work fine on this page.

With H.'s agreement, did a bit of re-arranging of where the various widgets/filters are, so that it all fits a bit better and makes a bit better logical sense.  Now await feedback, where users complain that it ought to be laid out exactly as it used to be (and then won't fit on narrow screen)... :(

Note that, the way the `FlowLayout` we use has to work, it is *not* going to be possible to place anything else on the (last) line to the right of the `FlowLayout` --- you have to regard that as occupying the whole of the last line it appears on.

**Comment by jnbarchan** [comment]
Now that's done, need to add the new filter for landlord...

**Comment by jnbarchan** [comment]
Added the new **Landlord** filter.

Even with the new "flow layout" space is at a premium for the filters (we don't want too many rows on a narrow screen).  Made all the filters have a maximum width (limits what is seen when the dropdown is not displayed, when it is the choices are shown full width --- at least under Linux/GNOME, hope same under Windows?), seems reasonable to me?

**Comment by jnbarchan** [comment]
Under Windows it turns out that if you have combo selection items wider than the box width they get truncated/interspersed with some kind of `...` for elision.  R. does not like this.  He says:

> I have just simulated R.'s small laptop and confirm that your current width of 130 is fine for all combo boxes except for Status, Landlord and Title grade, all of which need to be wider.  I suggest trying these three at 180.

**Comment by jnbarchan** [comment]
It turns out that we can use `QComboBox.view().setMinimumWidth()` to widen *just* the dropdown, which will work under Windows.

This will be introduced in Fix #248 .
