### ISSUE TITLE
Fault with RentCode white box on rent page

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#222]
Try entering a non existent rentcode in the box (ZPEA10) and press Return.  The text remains in the white box.  Now click the "Cycle through rents" Grey right arrow at top right.  You will move to the next rentcode but the non existent rentcode text remains in the white box.   I have also established that double clicking a row on the home page, the queries page or the MPR selected run page will, in each case, take you to the new rent on the rent page, but with the non existent rentcode text remaining in the white box.  I suggest that this is disconcerting and undesirable.

**Comment by hezmondo** [comment]
Laurence has largely fixed this problem, but leaving no message or effect whatsoever where a user types in a false rentcode and presses "Return", other than clearing the line edit.  We need a message/dialog such as "Rentcode ABC3 does not exist - please try again".  I suggest Laurence has a go at this and Jonathan checks the fix before it is pulled across to HJinn and Master.

**Comment by LaurenceLeo** [comment]
I have updated rentpage.py. Any "incorrect" rentcodes entered will cause the placeholder text in the rent search lineedit to change. So before searching it will be:

        "Find another rent"

After an incorrect search using **AAABBB** it would be:

        "No Rent code AAABBB"

Close this issue if you are content.

**Comment by LaurenceLeo** [comment]
ToDo: add autocomplete behaviour so that it list rentcodes from 3 characters or more.

-

**Comment by LaurenceLeo** [comment]
Done waiting for confirmation that there are no issues with rentcode history before closing

**Comment by hezmondo** [comment]
Still waiting or done waiting?
All seems to work fine for me.
    On Friday, 5 July 2019, 16:31:42 BST, Laurence Leo <notifications@github.com> wrote:  
 
 
Done waiting for confirmation that there are no issues with rentcode history before closing
