### ISSUE TITLE
Allow go to agent/property from Home page search rents table

### ISSUE THREAD

**Issue by jnbarchan** [hezmondo/Jinn#230]
On the Home page/search rents table (`rents/rentsearchpage.py`) there are columns for **Agent details** & **Property address**.  However, these do not have a context menu/double click item on data in the column to visit the corresponding agent/property.  In other places (e.g. **Head rents** page) we do have that.  I think we should have it here too.

At present to visit these one first has to go to the individual rent code page and then can use **Agent** or **Properties** widget to get there.  Those then open the agent/property *edit dialog*.  From the Home page I think it should go to the Agents/Properties *page* instead, filtered to the agent/property code.

**Comment by hezmondo** [comment]
Yes, that makes sense and would be an improvement.
    On Friday, 5 July 2019, 09:51:16 BST, jnbarchan <notifications@github.com> wrote:  
 
 
On the Home page/search rents table (rents/rentsearchpage.py) there are columns for Agent details & Property address. However, these do not have a context menu/double click item on data in the column to visit the corresponding agent/property. In other places (e.g. Head rents page) we do have that. I think we should have it here too.

At present to visit these one first has to go to the individual rent code page and then can use Agent or Properties widget to get there. Those then open the agent/property edit dialog. From the Home page I think it should go to the Agents/Properties page instead. filtered to the agent/property code.

**Comment by jnbarchan** [comment]
* Right-click context menu on these columns offers respective "Go to ..." actions.

* Right-click context menu on these columns also offers respective "Filter by ..." actions, as I sasw another column already had that.

* I have made the "Go to ..." actions on the Agent/Property columns be the *default*, so that double-clicking invokes it (double-clicking anywhere else on a row does the "Go to rent").  H. agreed with this.  However, I'm not sure, it *might* be that users don't want to think about where they double-click (as it used to be) and would prefer that to *always* stick to the old "Go to rent".  Have a play/let me know, we could retain the content menu item but stop it being the default double-click if preferred.
