### ISSUE TITLE
Resurrect Income/Bank Queries page output as it used to be

### ISSUE THREAD

**Issue by jnbarchan** [hezmondo/Jinn#242]
In Fix #159 (**Make Income Summary/Detail report be an exportable table to CSV/XLSX like everything else**) we made the income/banking output go to a `JTableView` so that it does not need its own code modules and can be exported to PDF/CSV/XLSX consistently like everywhere else.

One user does not like this: the old format used to put in a total, from a `JTableView` you must now export as above to get the total row.  He is not prepared to do that, and wants the old format back.

This means looking at the commit preceding Fix #159, which was https://github.com/hezmondo/Jinn/tree/32cc38c0fb2638f490a86ace88464ee4955e6665, and doing whatever to restore/reintegrate that, or something like it, into current master.  This is a shame, as I was asked to get rid of various modules to achieve that simplification which must now be restored or reintroduced in some form :(

It is not possible to have the `JTableView`s somehow have their own dedicated "total" row generically --- see my https://forum.qt.io/topic/104869/any-way-a-database-model-qtableview-could-have-an-extra-total-row.

@hezmondo 
I need clarification as to whether *all* the user wants is the introduction of a total row into the `JTableView` (which I *may* be able to create in specific cases relevant to where this is used only), or whether what they really want is aspect(s) of the old behaviour/layout re-introduced (and if so what exactly)?

**Comment by LaurenceLeo** [comment]
It might be a less elegant solution but couldn't we add an additional row after the filters had been applied. 

Would it be possible to add a setModelTotal() method that collects rowCount() and then iterates and produces a total. Then we can just insert a row at the end (or two if we want a blank row).

**Comment by jnbarchan** [comment]
* Made the `JTableView` have the total row in the on-screen table anyway.

* Changed `income`/`bankpreview.py` pages to now have a `JTabWidget` --- tab strip plus widget pages.  Put the `JTableView` on one page named titled **Table View**.

* Resurrected the income/bank old style layout.  Put that on another page titled **Report View**.  Made that the default/initial tab selected, to keep users happy.

* Resurrected the code for printing the **Report View** to PDF.  But not to CSV/XLSX, that is better handled by the exporter from the **Table View**.

* The **Export to CSV** buttons always do the **Table View** export, regardless of which tab page is being viewed.

* The **Export to PDF** buttons do the export of whichever of the two tab pages is currently being viewed.

* On the income page the **Detailed** report is very wide (many columns).  Although I made the printing able to output in landscape, it is still way too wide.  So for  **Detailed** the **PDF** button is hidden (just as it used to be).

* On the bank page the report is also wide (many columns).  Still too wide to print landscape.  So the **PDF** button is always hidden (just as it used to be).
