### ISSUE TITLE
Utilities/Settings - save changes to signature id results in error

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#278]
The settings manager now works without needing entries for Round prices and Round to, but if you change Signature id and then save your changes, the line saved in settings.ini is

signature_id = 1. Richard Hesmondhalgh

rather than:  signature_id = 1

Letter writing fails with the former setting.

**Comment by jnbarchan** [comment]
Fixed.

Should be tested, both in settings and in letter writing.
