### ISSUE TITLE
alteration to leases table needs tiny upgrade script

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#282]
The sql script is:

ALTER TABLE `yoda`.`leases` 
ADD COLUMN `StartRent` DECIMAL(8,2) NOT NULL DEFAULT '0.00' AFTER `StartDate`;
ADD COLUMN `RentCap` DECIMAL(8,2) NOT NULL DEFAULT '0.00' AFTER `UpliftType`;

**Comment by jnbarchan** [comment]
I will do this as specified if requested, *but*:

* Why does `StartRent` allow `NULL` if it has a `DEFAULT`?
* Why does `RentCap` allow `NULL` and have no `DEFAULT`?

I thought we had agreed that in Jinn fields like this would (tend to) have a `DEFAULT` and not allow `NULL`?

**Comment by hezmondo** [comment]
Der, Dunno.  Thank you for educating me that the script should in fact be
ALTER TABLE `yoda`.`leases` ADD COLUMN `StartRent` DECIMAL(8,2) NOT NULL DEFAULT '0.00' AFTER `StartDate`;ADD COLUMN `RentCap` DECIMAL(8,2) NOT NULL DEFAULT '0.00' AFTER `UpliftType`;  I have corrected the issue.



    On Friday, 8 November 2019, 07:57:27 GMT, jnbarchan <notifications@github.com> wrote:  
 
 
I will do this as specified if requested, but:
   
   - Why does StartRent allow NULL if it has a DEFAULT?
   - Why does RentCap allow NULL and have no DEFAULT?

I thought we had agreed that in Jinn fields like this would (tend to) have a DEFAULT and not allow NULL?
