### ISSUE TITLE
agents/agentspage/showRentsWidgets displays JNothingSelectedMessage("Select an agent to view associated rents for" when the agent is in fact known

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#68]
Not a huge deal but undesirable and irritating.  To test, go to rentcode ZVEC1 or any rent with an associated agent, double click on the agent details in the LE, click "view in agents tab".   The dialog only appears once in any Jinn session. Subsequent tests do not reveal the problem.

**Comment by jnbarchan** [comment]
More specifically: you must have gone into the Agents Page once _before_ you try "view in agents tab".
