### ISSUE TITLE
Default backup location needed for the Jinn Data folder

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#71]
The backup utilities are superb, but will be improved if each user can have a default backup location for the Jinn Data folder.  In my case, it will be "E:\\".   As each user PC might have a different preferred location, I suggest a third line in the FileSystem section of my settings.ini as follows:

[FileSystem]
root_data_directory = C:\Jinn\Data
root_local_directory = C:\Jinn\Local
backup_data_directory = E:\\

**Comment by jnbarchan** [comment]
Added [optional] `backup_data_directory =` to `settings.ini`, `[FileSystem]` section.
