### ISSUE TITLE
Prevent leaks from failing to delete QDialogs correctly

### ISSUE THREAD

**Issue by jnbarchan** [hezmondo/Jinn#76]
We are "leaking" `QDialog`s (at least, I'm assuming not `QWidget`s, they really ought to be on dialogs, maybe I'll check them sometime...).  We create and show a dialog dynamically, it goes out of scope but is not deleted.  Each time that code path is followed, a new instance is created, so we get multiple copies sitting around taking up memory.

These can be identified by using the `debugWidgetsInUse()` (it calls `QtWidgets.QApplication.allWidgets()`) I have written in `common/functions.py`, calling it at suitable points.  That function can be edited to provide whatever information wanted --- it's just to be used for debugging.

I can definitely see some dialogs being leaked  (e.g. `JNothingSelectedMessage`, `RentDatesDialog`) but others not.  I do not know (at present at least) _why_ some seem to leak while others do not.

From C++, if you `new`ed a `QDialog` you would `delete` it, but Python does not have `delete`.  We can use `QDialog.deleteLater()` if we need that.

For now I am taking a route to set auto-delete on all dialogs.  This should solve all these leaks.

The danger, I think, is that somewhere code displays a dialog, lets user interact and close, but then requests some data that was in a widget on the dialog (not just the button that was used to close it, that's returned OK).  I don't see how to track these down.  So we are going to run with the new auto-delete and see what happens over time.

All our dialogs are now derived from `JDialog`.  So:

- I'm making `JDialog.__init__()`call `self.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)` unconditionally.
- If & when we discover a dialog which must *not* auto-delete, after creating it code will need to:
a. `self.setAttribute(QtCore.Qt.WA_DeleteOnClose, False)`
b. ensure call `self.deleteLater()` after finishing collecting any data out of closed dialog.

**Comment by jnbarchan** [comment]
- I tracked down some of the places where code was leaking and changed code to not leak.
- I left a known case as per my post (https://forum.qt.io/topic/92825/python-pyqt-qdialog-with-connect-lambda-leaks)  - dialog.widget.signal.connect(lambda: function(self) OR self.function()).  Have not got time at moment to deal with nicely.
- Made our `JDialog(QDialog).__init__()` include `self.setAttribute(QtCore.Qt.WA_DeleteOnClose, False)`.  Seems to work form cases I tested, we'll have to see....

**Comment by hezmondo** [comment]
I have tested a series of Jinn dialogs with the relevant line of code left unhashed. 

I got no errors editing Agents, Head Rents, Money transactions, Landlords, Letters, Cases, Leases and Income postings.  

I got errors editing Rents, Actions, Deeds and Properties (all very old dialogs) and in trying to "Save to pdf" any webengine html letter or pay request.  I attach an md file of
[errorlog.txt](https://github.com/hezmondo/Jinn/files/2219130/errorlog.txt)
 my errors for each of these fails.

**Comment by hezmondo** [comment]
I have tested a series of Jinn dialogs with the relevant line of code left unhashed.

I got no errors editing Agents, Head Rents, Money transactions, Landlords, Letters, Cases, Leases and Income postings.

I got errors editing Rents, Actions, Deeds and Properties (all very old dialogs) and in trying to "Save to pdf" any webengine html letter or pay request. I attach an md file of my errors for each of these fails.
[errorlog.txt](https://github.com/hezmondo/Jinn/files/2219210/errorlog.txt)

**Comment by jnbarchan** [comment]
To get rid of these errors I have temporarily commented out the line
    `self.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)`
in our `JDialog.__init__()`.

However, this will mean that some dialogs will now be "leaking" again.  This needs sorting out, e.g. those dialogs which cannot afford to auto-delete-on-close must be identified, changed to set it to false explicitly after creation, and changed to explicitly delete it after they have retrieved vale from the dialog widgets.  Or, changed so that the values are copied out of the dialog before it is auto-deleted.

**Comment by jnbarchan** [comment]
We have a choice, between two evils:

1. Do _not_ make our dialogs' default be `self.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)`
In this case, nothing will go wrong, but we must track down leaks caused by, say, `connect(lambda: function(self))` and change that code so that it does not use such a lambda.

2. _Do_ make our dialogs' default be `self.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)`
In this case, nothing will leak, but we must track down wherever dialogs are shown & closed and change code to not auto-delete them until after we have collected information out of them.

Initially I was tempted by #1.  The trouble is, these _lambda-self_ "closures with yet another uncollectable reference to the widget" can be difficult to track down & rewrite, and there is nothing to stop a future code writer from re-introducing them.

So I'm going to go for #2.  There are also a lot of these to discover & track down, but hopefully I'll spot them all.  I will write one of my Python `with ...:` constructs to unset the auto-delete at the start and `deleteLater()` at the end around wherever a dialog is created, `exec()`ed and then values are still read to make it all neat/clear/safe.

**Comment by jnbarchan** [comment]
* Made `JDialog.__init__()` go `self.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)`.

* Did all dialogs which need to retrieve values after exit do so inside `with JDialog.delayedDeleteOnClose():`

* Did some refactoring to remove a few of the `connect(lambda: function(self))`s.

* Replaced most `JLineEdit`s I could find which are to edit decimal numbers be new `JDecimalEdit` class.  We should make sure we use some dedicated classes for `QLineEdit`s which are for numbers, it makes it all much easier to handle (e.g. `JDecimalEdit.value()`/`setValue()`).
