### ISSUE TITLE
Add basic formatting capability to editletterdialog.py

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#82]
As suggested by Jonathan, it will be very helpful to have a basic and simple formatting capability within the letter editing function.  We discussed following the md protocol.  I have taken a look and wonder if we might settle for one underscore either side for _italic_ and two underscores either side for __bold__.

**Comment by jnbarchan** [comment]
Agreed with Hez:

1. We must be careful that character sequences used cannot occur "by accident".  I am insisting on double-characters to ensure this:

* ``**``bold`**`=> **bold**
* ``__``underline`__`=> \_underline\_
* ``//``italic`//`=> _italic_

I have picked the sequences to be most like "what our end users might expect"! :)

2. These will be applied only inside certain `#`*Variable*`#` constructs.  The code calls these "Word Variables".  They are substituted during `buildLetterData()` & `producePrVariables()`. The variables to be done are:

* `#Clause1-5#` (`letters` table)
* `#ClauseA-B#` (`epr_template` table)
* `#ArearsClause#` (`epr_arrears_matrix` table)

They are all columns in various SQL tables, which have the text wanted.  `#Clause1-5#` can be edited from `editletterdialog.py`, but the others currently require direct editing from MySQL Workbench.

When the code finally hits doing the HTML `%`*Variable*`%` substitutions, it should see if the variable is one of the above and, if so, insert the HTML required.
