### ISSUE TITLE
suggested simplest fix for multiple signatories

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#90]
It is clear to me from looking at the code that I got part way towards allowing multiple signatories.  The existing letters_signatures table allows to store three signatures/signatories with unique ID, such as
```
1    Yours sincerely    Peter Clarke
2    Yours sincerely    Lorraine Clarke
3    Yours sincerely    Mike Clarke
```
In line 123 of `lettersfunctions.py`, the code arbitrarily sets the signature ID to 1:
```
signature_id = 1  # Enable this to be set in the ini / on the letter screen
```
In line 187 of `lettersfunctions.py`, the code goes on to set `Sig1` and `Sig2` to the values stored in the `letters_signatures` table for the respective signature ID, which is arbitrarily fixed as 1 at present.

So, the simplest fix is simply to add a further line in `settings.ini` for Signature ID, with `settingsmanagerdialog.py` offering the user the choice of whatever records it finds in the `letters_signatures` table.

**Comment by jnbarchan** [comment]
`settings.ini` now has a new section:
```
[Miscellaneous]
# signature_id: which SignatureID (from `letters_signatures` table) to use for letters (e.g. 1)
signature_id =
```
**Settings** Page has a dropdown offering a choice of the the rows from `letters_signatures` to choose from.

That setting is now used in `buildLetterData()`.
