### ISSUE TITLE
emailed multiple pay requests

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#91]
Our first phase of this project is to allow the user to **do a sequence of single pay requests from the MPR selected run page**.  JB has now dealt elegantly with this first of the two options, which is `Email single pay request/account for rentcode ABC1 without attachment` although **a small fix is needed so that the query is properly refreshed after each pay request is completed and the user is returned to the MPR selected run page**

The second option is `Email single pay request/account for rentcode ABC1 as a pdf attachment to an EPRD email`

My suggestion is that the code will **first** produce a pdf pay request for the rentcode in question according to all of the settings on the MPR selected run page but with "isLetter = true" and **second** take the user all the way to the email preview screen using lettertype EPRD and the default email address/addresses , "isEmail = true", and with the pdf pay request already attached.  This will mimic the current behaviour of the first option above whereby the user can then edit or add add a comment to the email text and then click "send email" and then be returned to the MPR selected run page and have the query refreshed.

When both of these options are working well, we can consider **the second phase of the project**, which will be for the user to **choose for either of the two options described above to be executed automatically for all the rents in the query results table**, obviously without any ability to intervene or to edit or add any comment to any email text.

**Comment by jnbarchan** [comment]
Implemented the "email without attachment" via context menu on pay request list item (appears only if item has licked email).

I'm pushing at this point to see what H. makes of it so far....

**Comment by jnbarchan** [comment]
* Did "with attachment" (as PDF or Docx as per toggle button on page, as normal) against `EPRD` email.

Obviously I had to change quite a bit of tricky code shared with other cases, like sending letters or individual emails, etc.  So to test it probably also needs testing all other routes which produce letters/emails as well....
